# Asprilo Generator Conda Recipe
{% set name = 'asprilo' %}
{% if environ.get('BUILD_RELEASE') %}
{%   set dev = false %}
{% else %}
{%   set dev = true %}
{% endif %}

package:
  name: asprilo-generator
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}

source:
  {% if dev %}
  {%   set rev = 'develop' %}
  {% else %}
  {%   set rev = 'master' %}
  {% endif %}
  git_rev: {{ rev }}
  git_url: https://github.com/potassco/{{ name }}.git

extra:
  channels:
    - potassco

requirements:
  build:
    - clingo
    - python>=3
    - pyyaml>=3.12
    - setuptools
  run:
    - clingo
    - python>=3
    - pyyaml>=3.12

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '') }}
  {% if dev %}
  string: py_{{ environ.get('GIT_BUILD_STR', '') }}
  {% endif %}
  noarch: python
  entry_points:
    - gen = generator.__main__:main

test:
  imports:
    - generator
  commands:
    - gen -h
    - gen -x 9 -y 6 -X 3 -Y 2 -s 9 -p 2 -r 2 -P 4 -u 16 -o 4 -C

about:
  home: https://asprilo.github.io/generator/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: An instance generator for asprilo
  description: |
    This is a generator of problem instances for asprilo.
  doc_url: https://asprilo.github.io/generator/
  dev_url: https://github.com/potassco/{{ name }}.git

