name: deploy re2c package

on:
  push:

jobs:
  build:
    name: deploy on ${{ matrix.os }} using python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: build

      - name: Install prerequisites
        shell: pwsh
        run: |
          conda config --set anaconda_upload yes
          conda install conda-build anaconda-client

      - name: Install macos SDK
        if: ${{ matrix.os == 'macos-latest' }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri 'https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.9.sdk.tar.xz' -OutFile 'MacOSX10.9.sdk.tar.xz'
          sudo tar xf MacOSX10.9.sdk.tar.xz -C /opt

      - name: print info
        shell: pwsh
        run: |
          conda info
          conda list

      - name: publish conda package (wip)
        shell: pwsh
        run: |
          conda build --channel potassco re2c
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

